# Generated by Django 2.0.6 on 2018-06-20 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recordtime', models.DateTimeField()),
                ('sequence', models.SmallIntegerField()),
                ('transcript', models.TextField()),
                ('confidence', models.DecimalField(decimal_places=3, max_digits=4)),
            ],
        ),
    ]
